[build]
  command="ng build"
  publish="dist/gumy/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false